#pragma once

#include "cinder/gl/gl.h"
#include "random.h"

using glm::vec2;

namespace animal_simulator {

/**
 * The animal object storing position and velocity.
 */
  class Herbivore {
  public:

    /**
     * Initializes a animal
     * @param position is the initial position of the animal
     * @param velocity is the initial velocity of the animal
     * @param radius is the permanent radius of the animal
     * @param mass is the permanent mass of the animal
     * @param color is the permanent color of the animal
     */
    Herbivore(vec2 position, vec2 velocity, float radius,
              float mass, ci::Color color);

    /**
     * Spawns multiple animals into a vector; controls what types of animals get made
     * @param count the number of animals we want to make.
     * @return The vector storing all of the generated animals.
     */
    static std::vector<Herbivore> SpawnHerbivores(size_t count);

    /**
     * Updates the animal position based on its velocity.
     */
    void Move();

    // Getters
    glm::vec2 GetPosition() const;
    glm::vec2 GetVelocity();
    float GetMass();
    float GetRadius() const;
    ci::Color GetColor() const;

    // Setter
    void SetVelocity(glm::vec2);

    /**
     * Calculates velocity changes given that "this" animal and animal_2 collide.
     * @param animal_2 the second animal to check a collision against.
     * @return the velocity vectors of the two animals.
     */
    std::vector<vec2> CalculateCollisionResults(Herbivore animal_2);

    /**
     * Calculates the distance between "this" animal and animal_2
     * @param animal_2 the animal to check distance against.
     * @return the distance between the two animals.
     */
    float CalculateDistance(Herbivore animal_2) const;



    /**
     * Checks whether a collision occurs against a rectangular container.
     * @param left_wall the left wall.
     * @param right_wall the right wall.
     * @param top_wall the top wall.
     * @param bottom_wall the bottom wall.
     */
    void CheckContainerCollision(float left_wall, float right_wall, float top_wall, float bottom_wall);

    /**
     * Calculates whether "this" animal is contacting animal_2.
     * @param animal_2 The second animal.
     * @return Whether "this" animal and animal_2 are in contact.
     */
    bool IsTouchingAnimal(Herbivore animal_2) const;

    /**
     * Calculates whether "this" animal is approaching animal_2.
     * @param animal_2 The second animal.
     * @return whether "this" animal is approaching animal_2.
     */
    bool ApproachesOtherAnimal(Herbivore animal_2);

  private:
    /**
     * Default spawn width.
     */
    static const size_t kDefaultWidth = 700;

    /**
     * Default spawn height.
     */
    static const size_t kDefaultHeight = 500;

    /**
     * Default spawn x coordinate.
     */
    static const int kDefaultXCoord = 100;

    /**
     * Default spawn y coordinate.
     */
    static const int kDefaultYCoord = 100;

    /**
     * Default spawn health.
     */
     static const int kDefaultHealth = 10;

     /**
      *
      */
     static const int kDefaultEnergy = 10;

    /**
     * Individual animal position, velocity, mass, radius, and color.
     */
    glm::vec2 position_;
    glm::vec2 velocity_;
    float mass_;
    float radius_;
    ci::Color color_;
    int health_;
    float energy_;


    /**
     * Calculates the new negated velocity given a wall collision.
     * @param x_or_y Whether we are negating the x value or the y value of the velocity.
     * @return The new velocity of a animal that has contacted a wall.
     */
    vec2 GetNegatedVelocity(bool x_or_y);

    /**
     * Creates animals one at a time.
     * @param new_radius the radius of the animal to be generated.
     * @param new_mass the mass of the animal to be generated.
     * @param new_color the color of the animal to be generated.
     * @return the Herbivore generated by the function.
     */
    static Herbivore GenerateRandomAnimal(float new_radius, float new_mass, cinder::Color new_color);

    /**
     * Helper function to apply collision formula.
     * @param animal_2 the animal that "this" is colliding against.
     * @return "this" animal's updated velocity given that it has collided with animal_2.
     */
    vec2 ApplyCollisionFormula(Herbivore animal_2);
  };

}